name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga el código
      - uses: actions/checkout@v4

      # 2. Instala Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Instala y construye
      - run: npm install
      - run: npm run build

      # 4. Despliega
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true